# LoRA Fine-Tuning FLAN-T5-base for Table-to-Text Summarization (ToTTo)

**Goal:** fine-tune `google/flan-t5-base` with LoRA to generate a single factual sentence
summarizing the highlighted cells of a Wikipedia table (ToTTo dataset).

**Pipeline:** raw ToTTo JSON -> prompt/target pairs -> tokenization -> LoRA fine-tuning -> save adapter -> inference & evaluation.

**Hardware:** local RTX 3060 (12GB VRAM), Ryzen 7 5600X, 32GB RAM - all training done on-device, no cloud.

> This notebook went through two rounds of debugging (mixed-precision NaNs, then LoRA-scaling/LR
> instability) before reaching the configuration below. See the **Debugging Notes** callouts
> throughout, and the **Summary & Next Steps** section at the end.
# Evaluation of diffrent fine tune strategies

## 1. Environment Setup

Confirm CUDA / GPU availability before doing anything expensive.

In [1]:
# GPU setup
import torch

# Check CUDA availability and GPU properties
print(f"torch version: {torch.__version__}")
print(f"CUDA version: {torch.version.cuda}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"GPU count: {torch.cuda.device_count()}")

if torch.cuda.is_available():
    print(f"GPU name: {torch.cuda.get_device_name(0)}")
    print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

torch version: 2.11.0+cu128
CUDA version: 12.8
CUDA available: True
GPU count: 1
GPU name: NVIDIA GeForce RTX 3060
VRAM: 12.9 GB

## 2. Data Preprocessing

Convert the raw ToTTo table JSON into flat `(prompt, target)` text pairs the model can consume.

### 2.1 Load raw ToTTo JSONL

In [2]:
# Loading datasets
from datasets import Dataset
import json, random
import os


def load_jsonl(path):
    with open(path) as f:
        return [json.loads(line) for line in f]

c:\Users\Youssef\Desktop\slm_fine_tune\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
train_data = load_jsonl("totto_data\\totto_train_data.jsonl")
validation_data = load_jsonl("totto_data\\totto_dev_data.jsonl")

### 2.2 Prompt Construction

Builds an instruction-style prompt: task description + page/section context + highlighted-cell coordinates + full table, asking the model to produce one factual sentence.

In [ ]:
def get_header_block_end(table):
    """The header block is the maximal prefix of rows where EVERY cell is
    is_header=True. This correctly excludes tables where only the first
    COLUMN is marked as a row-label inside data rows (e.g. Chicago Bears'
    'Year' column) — those rows are only partially header-marked, so they
    fail the 'every cell' test and the block stops before them."""
    end = 0
    for row in table:
        if row and all(cell.get("is_header") for cell in row):
            end += 1
        else:
            break
    return end


def expand_header_row(row):
    """Expands a header row's cells across their column_span so position i
    lines up with actual column i, matching data-row layout."""
    expanded = []
    for cell in row:
        expanded.extend([cell["value"]] * max(cell.get("column_span", 1), 1))
    return expanded


def is_locally_uniform(table, header_block_end, target_row_idx, header_width):
    """Only require rows BETWEEN the header and the target to match the
    header's width. A width change AFTER the target row (e.g. a second
    inline sub-table starting later, like Indonesia's 'No/City' header)
    doesn't make the target's own column position untrustworthy."""
    for row in table[header_block_end:target_row_idx + 1]:
        if len(row) != header_width:
            return False
    return True


def get_column_header(table, target_row_idx, target_col_idx):
    header_block_end = get_header_block_end(table)
    if header_block_end == 0 or target_row_idx < header_block_end:
        return ""
    if not is_locally_uniform(table, header_block_end, target_row_idx, len(table[header_block_end - 1])):
        return ""  # can't trust positional alignment in this table: skip, don't guess

    parts = []
    for row in table[:header_block_end]:
        expanded = expand_header_row(row)
        if target_col_idx >= len(expanded):
            return ""
        val = expanded[target_col_idx].strip()
        if val and (not parts or parts[-1] != val):
            parts.append(val)
    return " ".join(parts)

In [ ]:
# Building the prompt for the model

def build_prompt(sample):
    """ Builds a prompt for the model to summarize the table based on the given input. """
    table = sample["table"]
    highlighted_cells = sample["highlighted_cells"]
    final_sentence = sample["sentence_annotations"][0]["final_sentence"]

    # Explicit row-index prefix: lookup, not counting.
    table_str = "\n".join(
        f"[{i}] " + "\t".join(cell["value"] for cell in row)
        for i, row in enumerate(table)
    )

    # Column header label, only when it can be trusted (see above).
    highlighted_lines = []
    for row, col in highlighted_cells:
        header = get_column_header(table, row, col)
        label = f" ({header})" if header else ""
        highlighted_lines.append(f"Row: {row}, Column: {col}{label}")
    highlighted_str = "\n".join(highlighted_lines)

    prompt = f"""Task:
Generate a single factual sentence describing the information contained in the highlighted cells.
Use only information provided below.
Do not invent facts.\n"""
    if sample["table_page_title"]:
        prompt += f"Page Title:\n{sample['table_page_title']}\n"
    if sample["table_section_title"]:
        prompt += f"Section Title:\n{sample['table_section_title']}\n"
    if sample["table_section_text"]:
        prompt += f"Additional Context:\n{sample['table_section_text']}\n"
    if sample["highlighted_cells"]:
        prompt += f"Highlighted Cells:\n{highlighted_str}\n"

    prompt += f"Table:\n{table_str}\nAnswer:\n"
    return prompt

In [16]:
# Sanity check: Print a random sample prompt
random_sample = random.choice(train_data)
prompt = build_prompt(random_sample)
print(prompt)

Task:
Generate a single factual sentence describing the information contained in the highlighted cells.
Use only information provided below.
Do not invent facts.
Page Title:
List of Presidents of the National Convention
Section Title:
Moderate Phase: September 1792 – June 1793
Additional Context:
Initially, La Marais, or The Plain, a moderate, amorphous group, controlled the Convention. At the first session, held on 20 September 1792, the elder statesman Philippe Rühl presided over the session.
Highlighted Cells:
Row: 20, Column: 1 (Dates)
Row: 20, Column: 2 (Name)
Table:
[0] Image	Dates	Name	Fate
[1] AduC 150 Ruhl (P.J., 1737-1795).JPG	20 September 1792	Philippe Rühl	Suicide, 29/30 May 1795
[2] -	20 September 1792 – 4 October 1792	Jérôme Pétion de Villeneuve	Botched suicide, guillotined 18 June 1794
[3] AduC 139 Lacroix (J.F. de, 1754-1794).JPG	4 October 1792 – 18 October 1792	Jean-François Delacroix	Guillotined with Georges Danton, 5 April 1794
[4] -	18 October 1792 – 1 November 1792	Marguerite-Élie Guadet	Guillotined 17 June 1794
[5] -	1 November 1792 – 15 November 1792	Marie-Jean Hérault de Séchelles	Guillotined with Georges Danton, 5 April 1794
[6] -	15 November 1792 – 29 November 1792	Henri Grégoire	Died 28 May 1831
[7] -	29 November 1792 – 13 December 1792	Bertrand Barère de Vieuzac	Died 13 January 1841
[8] portrait of Jacques defermon	13 December 1792 – 27 December 1792	Jacques Defermon des Chapelieres	20 June 1831
[9] -	27 December 1792 – 10 January 1793	Jean-Baptiste Treilhard	Died 1 December 1810
[10] -	10 January 1793 – 24 January 1793	Pierre Victurnien Vergniaud	31 October 1793, guillotined.
[11] -	24 January 1793 – 7 February 1793	Jean-Paul Rabaut Saint-Étienne	5 December 1793, guillotined
[12] 	7 February 1793 – 21 February 1793	Jean-Jacques Bréard, dit Bréard-Duplessis	2 January 1840
[13] -	21 February 1793 – 7 March 1793	Edmond Louis Alexis Dubois-Crancé	29 June 1814
[14] Armand Gensonné IMG 2447.JPG	7 March 1793 – 21 March 1793	Armand Gensonné	31 October 1793, guillotined
[15] AduC 240 Debry (A.J., 1766-1834).JPG	21 March 1793 – 4 April 1793	Jean Antoine Joseph Debry	6 January 1834, Paris
[16] 	4 April 1793 – 18 April 1793	Jean-François-Bertrand Delmas	Disappeared 19 August 1798
[17] 	18 April 1793 – 2 May 1793	Marc David Alba Lasource	31 October 1793, guillotined with the Girondists
[18] Boyer-Fonfrède, Jean-Baptiste.JPG	2 May 1793 – 16 May 1793	Jean-Baptiste Boyer-Fonfrède	31 October 1793, guillotined
[19] -	16 May 1793 – 30 May 1793	Maximin Isnard	12 March 1825
[20] 	30 May 1793 – 13 June 1793	François-René-Auguste Mallarmé	25 July 1835
Answer:

**Observation:** the prompt design deliberately includes page title, section title, and
highlighted-cell coordinates as separate labeled blocks (rather than flattening everything into
the table) so the model has an explicit signal for *which* cells matter.

### 2.3 Convert & Persist Processed Dataset

Flatten every example to `{id, prompt, target}` and write to disk so tokenization/training can be re-run without redoing this step.

In [17]:
# Convert the data from the original format to json with two fields: "prompt" and "target"
def convert_data(data):
    return [
        {
            "id": sample["example_id"],
            "prompt": build_prompt(sample),
            "target": sample["sentence_annotations"][0]["final_sentence"],
        }
        for sample in data
    ]
train_data = convert_data(train_data)
validation_data = convert_data(validation_data)

In [19]:
# save the train_data to a json file
def save_jsonl(data, path):
    with open(path, "w", encoding="utf-8") as f:
        for sample in data:
            f.write(json.dumps(sample, ensure_ascii=False) + "\n")

save_jsonl(train_data, "totto_data\\train.jsonl")
save_jsonl(validation_data, "totto_data\\validation.jsonl")

**Observation:** persisting `train.jsonl` / `validation.jsonl` separately from the raw ToTTo
files decouples prompt-engineering iteration from training, the prompt format can be changed here
without touching the fine-tuning cells below, as long as this cell is re-run first.

## 3. Base Model & Tokenizer Loading

In [1]:
# Load the model and tokenizer
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, BitsAndBytesConfig
import torch
save_directory = "./models/flan-t5-base-local"

# Load from local directory
tokenizer = AutoTokenizer.from_pretrained(save_directory, local_files_only=True)
model = AutoModelForSeq2SeqLM.from_pretrained(
    save_directory,
    device_map="auto",           # Automatically place model layers
    trust_remote_code=True,      # Required for some models
    dtype=torch.bfloat16,        # Use bfloat16 for non-quantized parts
)

c:\Users\Youssef\Desktop\slm_fine_tune\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 282/282 [00:00<00:00, 793.64it/s]
[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

**Debugging note:** the model is loaded directly in **`bfloat16`**. Loading in bf16 up front matters: an earlier
version of this notebook mixed a bf16-loaded model with `fp16=True` in the `Trainer`, and that
precision mismatch caused the training loss to go to `NaN` (T5's activations have a dynamic range
that overflows float16 but not bfloat16). Keeping the load dtype and the `Trainer`'s mixed-precision
flag consistent (bf16 <-> bf16) is what fixed it; see Section 6.

## 4. Dataset Loading & Tokenization

In [2]:
# Load the datasets
from datasets import load_dataset

dataset = load_dataset(
    "json",
    data_files={
        "train": "totto_data/train.jsonl",
        "validation": "totto_data/validation.jsonl"
    }
)

print(dataset["train"][0])
print(dataset["validation"][0])

Generating train split: 120761 examples [00:01, 103830.48 examples/s]
Generating validation split: 7700 examples [00:00, 111491.72 examples/s]

{'id': 1762238357686640028, 'prompt': 'Task:\nGenerate a single factual sentence describing the information contained in the highlighted cells.\nUse only information provided below.\nDo not invent facts.\nPage Title:\nList of 8/9 PM telenovelas of Rede Globo\nSection Title:\n2000s\nHighlighted Cells:\nRow: 13, Column: 2 (Title)\nTable:\n[0] #\tRun\tTitle\tChapters\tAuthor\tDirector\tIbope Rating\n[1] 59\tJune 5, 2000— February 2, 2001\tLaços de Família\t209\tManoel Carlos\tRicardo Waddington\t44.9\n[2] 60\tFebruary 5, 2001— September 28, 2001\tPorto dos Milagres\t203\tAguinaldo Silva Ricardo Linhares\tMarcos Paulo Simões\t44.6\n[3] 61\tOctober 1, 2001— June 14, 2002\tO Clone\t221\tGlória Perez\tJayme Monjardim\t47.0\n[4] 62\tJune 17, 2002— February 14, 2003\tEsperança\t209\tBenedito Ruy Barbosa\tLuiz Fernando\t37.7\n[5] 63\tFebruary 17, 2003— October 10, 2003\tMulheres Apaixonadas\t203\tManoel Carlos\tRicardo Waddington\t46.6\n[6] 64\tOctober 13, 2003— June 25, 2004\tCelebridade\t221\tGilberto Braga\tDennis Carvalho\t46.0\n[7] 65\tJune 28, 2004— March 11, 2005\tSenhora do Destino\t221\tAguinaldo Silva\tWolf Maya\t50.4\n[8] 66\tMarch 14, 2005— November 4, 2005\tAmérica\t203\tGlória Perez\tJayme Monjardim Marcos Schechtman\t49.4\n[9] 67\tNovember 7, 2005— July 7, 2006\tBelíssima\t209\tSílvio de Abreu\tDenise Saraceni\t48.5\n[10] 68\tJuly 10, 2006— March 2, 2007\tPáginas da Vida\t203\tManoel Carlos\tJayme Monjardim\t46.8\n[11] 69\tMarch 5, 2007— September 28, 2007\tParaíso Tropical\t179\tGilberto Braga Ricardo Linhares\tDennis Carvalho\t42.8\n[12] 70\tOctober 1, 2007— May 31, 2008\tDuas Caras\t210\tAguinaldo Silva\tWolf Maya\t41.1\n[13] 71\tJune 2, 2008— January 16, 2009\tA Favorita\t197\tJoão Emanuel Carneiro\tRicardo Waddington\t39.5\n[14] 72\tJanuary 19, 2009— September 11, 2009\tCaminho das Índias\t203\tGlória Perez\tMarcos Schechtman\t38.8\n[15] 73\tSeptember 14, 2009— May 14, 2010\tViver a Vida\t209\tManoel Carlos\tJayme Monjardim\t35.6\nAnswer:\n', 'target': 'A Favorita is the telenovela aired in the 9 pm timeslot.'}
{'id': 7391450717765563190, 'prompt': 'Task:\nGenerate a single factual sentence describing the information contained in the highlighted cells.\nUse only information provided below.\nDo not invent facts.\nPage Title:\nList of Governors of South Carolina\nSection Title:\nGovernors under the Constitution of 1868\nAdditional Context:\nParties Democratic Republican\nHighlighted Cells:\nRow: 3, Column: 0\nRow: 3, Column: 2\nRow: 3, Column: 3\nTable:\n[0] #\tGovernor\tTook Office\tLeft Office\tLt. Governor\tParty\tNotes\n[1] 74\t-\tRobert Kingston Scott\tJuly 6, 1868\tDecember 7, 1872\tLemuel Boozer Alonzo J. Ransier\tRepublican\t\n[2] 75\t-\tFranklin J. Moses, Jr.\tDecember 7, 1872\tDecember 1, 1874\tRichard Howell Gleaves\tRepublican\t\n[3] 76\t-\tDaniel Henry Chamberlain\tDecember 1, 1874\tDecember 14, 1876\tRichard Howell Gleaves\tRepublican\tClaimed Governorship after 1876 election\n[4] 77\t-\tWade Hampton III\tDecember 14, 1876\tFebruary 26, 1879\tWilliam Dunlap Simpson\tDemocratic\tResigned\n[5] 78\t-\tWilliam Dunlap Simpson\tFebruary 26, 1879\tSeptember 1, 1880\tJohn D. Kennedy\tDemocratic\tNot elected\n[6] 79\t-\tThomas Bothwell Jeter\tSeptember 1, 1880\tNovember 30, 1880\tvacant\tDemocratic\t\n[7] 80\t-\tJohnson Hagood\tNovember 30, 1880\tDecember 1, 1882\tJohn D. Kennedy\tDemocratic\t\n[8] 81\t-\tHugh Smith Thompson\tDecember 1, 1882\tJuly 10, 1886\tJohn Calhoun Sheppard\tDemocratic\tResigned\n[9] 82\t-\tJohn Calhoun Sheppard\tJuly 10, 1886\tNovember 30, 1886\tvacant\tDemocratic\tNot elected\n[10] 83\t-\tJohn Peter Richardson III\tNovember 30, 1886\tDecember 4, 1890\tWilliam Mauldin\tDemocratic\t\n[11] 84\t-\tBenjamin Ryan Tillman\tDecember 4, 1890\tDecember 4, 1894\tEugene Gary W.H. Timmerman\tDemocratic\t\n[12] 85\t-\tJohn Gary Evans\tDecember 4, 1894\tJanuary 18, 1897\tW.H. Timmerman\tDemocratic\t\nAnswer:\n', 'target': 'Daniel Henry Chamberlain was the 76th Governor of South Carolina from 1874.'}

In [3]:
# NOTE: no explicit -100 masking of pad tokens is needed here - DataCollatorForSeq2Seq
# (instantiated in Section 6) pads labels with -100 automatically at batch time.
# Tokenize the dataset
def preprocess(examples):
    model_inputs = tokenizer(
        examples["prompt"],
        max_length=512,
        truncation=True,
    )

    labels = tokenizer(
        text_target=examples["target"],
        max_length=64,
        truncation=True,
    )

    model_inputs["labels"] = labels["input_ids"]

    return model_inputs

In [4]:
tokenized_dataset = dataset.map(
    preprocess,
    batched=True,
    remove_columns=dataset["train"].column_names
)

Map: 100%|██████████| 120761/120761 [00:51<00:00, 2360.62 examples/s]
Map: 100%|██████████| 7700/7700 [00:03<00:00, 2269.32 examples/s]

In [5]:
print(tokenized_dataset["train"][0])
print(tokenized_dataset["validation"][0])
# print stats 
print(f"Number of training samples: {len(tokenized_dataset['train'])}")
print(f"Number of validation samples: {len(tokenized_dataset['validation'])}")

{'input_ids': [16107, 10, 6939, 2206, 3, 9, 712, 685, 3471, 7142, 3, 16012, 8, 251, 6966, 16, 8, 12566, 2640, 5, 2048, 163, 251, 937, 666, 5, 531, 59, 16, 2169, 6688, 5, 5545, 11029, 10, 6792, 13, 505, 87, 1298, 3246, 3, 1931, 5326, 15, 521, 7, 13, 1624, 15, 9840, 115, 32, 5568, 11029, 10, 2766, 7, 16388, 15, 26, 7845, 7, 10, 11768, 10, 10670, 29926, 10, 204, 41, 382, 155, 109, 61, 4398, 10, 784, 632, 908, 1713, 7113, 11029, 8647, 7, 10236, 2578, 27, 115, 32, 855, 21662, 784, 536, 908, 3, 3390, 1515, 7836, 2766, 318, 2083, 3547, 4402, 325, 24065, 7, 20, 1699, 51, 2, 40, 23, 9, 460, 1298, 1140, 32, 15, 40, 19783, 2403, 6043, 32, 3129, 30557, 314, 27336, 784, 357, 908, 1640, 2083, 7836, 4402, 318, 1600, 13719, 4402, 3625, 32, 103, 7, 8573, 9, 11176, 3, 23330, 71, 17996, 138, 26, 32, 26551, 2403, 6043, 32, 6741, 3272, 15, 7, 16902, 7, 1838, 32, 6619, 2, 15, 7, 314, 25652, 784, 519, 908, 3, 4241, 1797, 1914, 4402, 318, 1515, 11363, 4407, 411, 4779, 782, 204, 2658, 350, 40, 4922, 52, 23, 9, 1915, 457, 9373, 526, 2963, 5670, 26, 603, 314, 26346, 784, 591, 908, 3, 4056, 1515, 12864, 4407, 318, 2083, 11363, 3888, 1122, 883, 152, 11666, 460, 1298, 2798, 11272, 32, 2770, 63, 11038, 32, 7, 9, 2318, 23, 172, 28989, 6862, 5, 940, 784, 755, 908, 3, 3891, 2083, 12864, 3888, 318, 1797, 10372, 3888, 10094, 88, 60, 7, 5085, 9, 2407, 32, 18089, 7, 3, 23330, 1140, 32, 15, 40, 19783, 2403, 6043, 32, 3129, 30557, 314, 28833, 784, 948, 908, 6687, 1797, 10670, 3888, 318, 1515, 14105, 4406, 26071, 15644, 15, 204, 2658, 24378, 32, 3497, 122, 9, 18563, 1184, 2165, 107, 32, 314, 22642, 784, 940, 908, 7123, 1515, 13719, 4406, 318, 1332, 9694, 3105, 4892, 21783, 103, 19344, 32, 204, 2658, 71, 17996, 138, 26, 32, 26551, 9091, 932, 9, 305, 22776, 784, 927, 908, 3, 3539, 1332, 11363, 3105, 318, 1671, 6464, 3105, 736, 5134, 658, 3, 23330, 350, 40, 4922, 52, 23, 9, 1915, 457, 9373, 526, 2963, 5670, 26, 603, 16902, 7, 1880, 12041, 348, 9526, 5, 591, 784, 1298, 908, 3, 3708, 1671, 7973, 3105, 318, 1718, 7973, 3581, 5622, 2, 7, 7, 603, 9, 460, 1298, 180, 2, 40, 2099, 32, 20, 891, 60, 76, 3128, 159, 15, 12969, 18778, 314, 19253, 784, 1714, 908, 3, 3651, 1718, 10372, 3581, 318, 1332, 3547, 4101, 276, 2975, 19604, 7, 836, 19575, 9, 3, 23330, 1140, 32, 15, 40, 19783, 9373, 526, 2963, 5670, 26, 603, 9668, 5, 927, 784, 2596, 908, 3, 3951, 1332, 7836, 4101, 318, 1600, 13719, 4101, 4734, 2, 7, 32, 28907, 3, 26593, 24378, 32, 3497, 122, 9, 2403, 6043, 32, 6741, 3272, 15, 7, 18563, 1184, 2165, 107, 32, 314, 19419, 784, 2122, 908, 2861, 1797, 1914, 4101, 318, 932, 12074, 2628, 970, 9, 7, 1184, 9, 7, 3, 15239, 71, 17996, 138, 26, 32, 26551, 9091, 932, 9, 314, 11039, 784, 2368, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [71, 16717, 155, 9, 19, 8, 3, 1931, 5326, 15, 521, 3, 2378, 26, 16, 8, 668, 6366, 648, 3171, 5, 1]}
{'input_ids': [16107, 10, 6939, 2206, 3, 9, 712, 685, 3471, 7142, 3, 16012, 8, 251, 6966, 16, 8, 12566, 2640, 5, 2048, 163, 251, 937, 666, 5, 531, 59, 16, 2169, 6688, 5, 5545, 11029, 10, 6792, 13, 10510, 7, 13, 1013, 5089, 5568, 11029, 10, 10510, 7, 365, 8, 11378, 13, 507, 3651, 11180, 1193, 6327, 10, 17450, 7, 10021, 8994, 16388, 15, 26, 7845, 7, 10, 11768, 10, 6180, 29926, 10, 3, 632, 11768, 10, 6180, 29926, 10, 204, 11768, 10, 6180, 29926, 10, 220, 4398, 10, 784, 632, 908, 1713, 10510, 304, 1825, 2126, 14298, 2126, 301, 17, 5, 10510, 3450, 2507, 7, 784, 536, 908, 3, 4581, 3, 18, 2715, 26133, 4972, 1718, 8580, 507, 3651, 1882, 7973, 507, 5865, 312, 51, 76, 15, 40, 1491, 32, 2558, 901, 32, 20547, 446, 5, 15039, 7, 972, 8994, 784, 357, 908, 6374, 3, 18, 16079, 446, 5, 20064, 6, 8206, 5, 1882, 7973, 507, 5865, 1882, 1914, 507, 4581, 4117, 571, 3820, 350, 109, 16001, 8994, 784, 519, 908, 3, 3959, 3, 18, 4173, 7780, 9572, 521, 77, 1882, 1914, 507, 4581, 1882, 11363, 507, 3959, 4117, 571, 3820, 350, 109, 16001, 8994, 4779, 8287, 10510, 2009, 227, 507, 3959, 4356, 784, 591, 908, 3, 4013, 3, 18, 26765, 24341, 6289, 1882, 11363, 507, 3959, 2083, 13597, 507, 4440, 4599, 6393, 8478, 21965, 10021, 419, 15532, 784, 755, 908, 3, 3940, 3, 18, 4599, 6393, 8478, 21965, 2083, 13597, 507, 4440, 1600, 1914, 507, 2079, 1079, 309, 5, 14532, 10021, 933, 8160, 784, 948, 908, 3, 4440, 3, 18, 3576, 2867, 2091, 1022, 449, 1600, 1914, 507, 2079, 1671, 11558, 507, 2079, 14333, 10021, 784, 940, 908, 2775, 3, 18, 5891, 1626, 10452, 1671, 11558, 507, 2079, 1882, 1914, 507, 4613, 1079, 309, 5, 14532, 10021, 784, 927, 908, 3, 4959, 3, 18, 11560, 107, 3931, 14653, 1882, 1914, 507, 4613, 1718, 10372, 507, 3840, 1079, 3104, 9492, 29, 451, 1572, 986, 10021, 419, 15532, 784, 1298, 908, 3, 4613, 3, 18, 1079, 3104, 9492, 29, 451, 1572, 986, 1718, 10372, 507, 3840, 1671, 11558, 507, 3840, 14333, 10021, 933, 8160, 784, 1714, 908, 3, 4591, 3, 18, 1079, 2737, 4117, 739, 6289, 1671, 11558, 507, 3840, 1882, 6464, 507, 2394, 4599, 1534, 83, 2644, 10021, 784, 2596, 908, 3, 4608, 3, 18, 15717, 7826, 22067, 348, 1882, 6464, 507, 2394, 1882, 6464, 507, 4240, 18281, 15, 13439, 549, 5, 566, 5, 332, 12174, 348, 10021, 784, 2122, 908, 11989, 3, 18, 1079, 13439, 18305, 1882, 6464, 507, 4240, 1762, 14985, 507, 4327, 549, 5, 566, 5, 332, 12174, 348, 10021, 11801, 10, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [4173, 7780, 9572, 521, 77, 47, 8, 3, 3959, 189, 10510, 13, 1013, 5089, 45, 507, 4581, 5, 1]}
Number of training samples: 120761
Number of validation samples: 7700

**Observation:** 120,761 training / 7,700 validation examples after tokenization. Inputs are
truncated at 384 tokens, targets at 64 tokens (single-sentence summaries are short, so 64 is generous).

## 5. Sequence Length Analysis

Before committing to `max_length=384` above, check whether that's actually a reasonable cutoff for this data.

In [ ]:
import numpy as np

lengths = [len(x["input_ids"]) for x in tokenized_dataset["train"]]

print(f"Average length: {np.mean(lengths):.1f}")
print(f"Median length : {np.median(lengths):.1f}")
print(f"95th percentile: {np.percentile(lengths,95):.1f}")
print(f"Maximum length: {np.max(lengths)}")

Average length: 354.0
Median length : 376.0
95th percentile: 512.0
Maximum length: 512

In [ ]:
lengths = [
    len(tokenizer(x["prompt"]).input_ids)
    for x in dataset["train"]
]

import numpy as np

print("<=256 :", np.mean(np.array(lengths) <= 256))
print("<=320 :", np.mean(np.array(lengths) <= 320))
print("<=384 :", np.mean(np.array(lengths) <= 384))
print("<=448 :", np.mean(np.array(lengths) <= 448))
print("<=512 :", np.mean(np.array(lengths) <= 512))

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (566 > 512). Running this sequence through the model will result in indexing errors

<=256 : 0.3599589271370724
<=320 : 0.44387674828794066
<=384 : 0.5077053022084944
<=448 : 0.5625988522784674
<=512 : 0.6106855690164871

**Note:** only **~51%** of training prompts fit within 384 tokens,
and the raw prompt-length check confirms some examples exceed the model's absolute 512-token limit
(hence the `Token indices sequence length is longer than...` warning). Nearly half of the training
tables are being **truncated**, which means the model sometimes never sees the exact highlighted
cells it's supposed to summarize, if they fall late in a long table. This doesn't break training,
but it likely caps achievable quality. If time allows, re-running with `max_length=512` (covers
~61%) or restructuring the prompt to move highlighted cells before the full table dump would be a
worthwhile follow-up experiment.

## 6. LoRA Configuration

In [6]:
# LoRA configuration
from peft import LoraConfig, TaskType, get_peft_model
peft_config = LoraConfig(
    r=8,                                # Rank of the low-rank matrices
    lora_alpha=16,                      # Scaling factor for the low-rank matrices
    target_modules=["q", "v"],          # Target modules for LoRA
    lora_dropout=0.1,                   # Dropout rate for LoRA layers
    bias="none",                        # No bias in LoRA layers
    task_type=TaskType.SEQ_2_SEQ_LM,    # Task type for encoder-decoder models
    )

model = get_peft_model(model, peft_config)

W0722 04:36:12.613000 23348 Lib\site-packages\torch\utils\flop_counter.py:29] triton not found; flop counting will not work for triton kernels

In [ ]:
model.print_trainable_parameters()

trainable params: 884,736 || all params: 248,462,592 || trainable%: 0.3561

**Debugging note:** `r=8, lora_alpha=16` gives an effective scaling factor of
`alpha/r = 2x`. This is the **corrected** configuration; an earlier attempt used `r=4, lora_alpha=32`
(an 8x scaling factor), which combined with `learning_rate=2e-4` produced an effective update
magnitude large enough to blow up gradients mid-training (loss -> `inf` -> `NaN`, masked by the
`Trainer`'s default `logging_nan_inf_filter` as a misleading flat `0.000000` training loss).
Only **884,736 / 248,462,592** parameters (0.36%) are trainable; LoRA touches only the `q`/`v`
attention projections, which is why this fits comfortably in 12GB VRAM even with room for batch
size 16.

## 7. Training Configuration & Sanity Checks

### 7.1 Trainer Setup

In [ ]:
# Trainer configuration
import os
from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments, EarlyStoppingCallback, DataCollatorForSeq2Seq
os.environ["TENSORBOARD_LOGGING_DIR"] = "./logs"

training_args = Seq2SeqTrainingArguments(
    output_dir="./results",

    # Training
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    gradient_accumulation_steps=2,
    gradient_checkpointing=False,
    learning_rate=1e-4,
    weight_decay=0.01,
    warmup_steps=500,
    lr_scheduler_type="cosine",

    # Logging
    logging_steps=1,
    save_steps=1000,
    eval_steps=500,
    eval_strategy="epoch",
    save_strategy="epoch",
    train_sampling_strategy="group_by_length",
    logging_first_step=True,   
    logging_nan_inf_filter=False,

    # Generation
    predict_with_generate=False,
    generation_max_length=32,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    # Mixed precision
    fp16=False,
    bf16=True, 

    # Optimizer
    optim="adamw_torch", # for qlora paged_adamw_32bit

    seed=67,        # Set a random seed for reproducibility

    report_to="tensorboard",
)


data_collator = DataCollatorForSeq2Seq(
    tokenizer,
    model=model,
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    processing_class=tokenizer,
    data_collator=data_collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

**Observation:** key flags and why they're set this way:
- `bf16=True, fp16=False` : matches the model's load dtype (see Section 3); this is what actually
  fixed the original NaN issue.
- `logging_nan_inf_filter=False` : deliberately disabled so a real `NaN`/`inf` loss shows up
  immediately in the logs instead of being silently smoothed into the running average. Safe to
  flip back to `True` for a longer, already-validated production run.
- `logging_steps=1` : verbose on purpose, to closely watch the loss curve for signs of instability
  during the first debugging runs. Worth raising back to `~50` once a config is trusted, to reduce
  notebook/log clutter.
- `load_best_model_at_end=True` + `metric_for_best_model="eval_loss"` : ensures the checkpoint
  saved at the end is the best-performing one on validation loss, not just the last epoch.

### 7.2 Pre-Training Sanity Check

Before committing ~2h47m to a full training run, confirm the pipeline produces a finite, reasonable loss on an untouched batch.

In [ ]:
model.eval()
batch = next(iter(trainer.get_train_dataloader()))
batch = {k: v.to(model.device) for k, v in batch.items()}
with torch.no_grad():
    out = model(**batch)
print("loss on a fresh, untrained batch:", out.loss)

loss on a fresh, untrained batch: tensor(2.3594, device='cuda:0', dtype=torch.bfloat16)

**Observation:** 
The initial training loss was 2.36, which is a normal finite value. This confirmed that the dataset and labels were prepared correctly and that the earlier NaN errors were caused by the training configuration rather than the data itself. Since FLAN-T5 is already a pre-trained language model, it starts with useful language knowledge instead of learning from scratch, which explains why the initial loss is relatively low.

## 8. Fine-Tuning

In [ ]:
# Fine-tuning the model
trainer.train()

TrainOutput(global_step=11322, training_loss=3.722759708112003, metrics={'train_runtime': 10004.4223, 'train_samples_per_second': 36.212, 'train_steps_per_second': 1.132, 'total_flos': 1.4555275378947072e+17, 'train_loss': 3.722759708112003, 'epoch': 3.0})

**Observation:**

The model completed all 3 training epochs successfully in about 2 hours and 47 minutes without any errors (such as NaN values), showing that the previous training issues were fixed. The validation loss decreased from 1.64 to 1.59, then to 1.58, which means the model continued to improve during training. However, the improvement became much smaller in the last epoch, indicating that the model was close to reaching its best performance with the current training settings. The slight increase in training loss during the last epoch is normal and can be caused by LoRA dropout and the different batches used during training. Since the validation loss continued to decrease, there is no sign of overfitting.

**Note:** The reported losses are calculated using the correct target sentences (teacher forcing). While they indicate that the model has learned the task, they do not directly measure the quality of the generated summaries. Additional evaluation metrics such as ROUGE and BLEU are needed to assess the final model performance.

## 9. Save Fine-Tuned Adapter

In [ ]:
# Save the fine-tuned model
model.save_pretrained("./models/flan-t5-base-totto-lora-finetuned")

## 10. Evaluation & Inference

### 10.1 Reload Base Model + LoRA Adapter

In [1]:
from peft import PeftModel
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
import torch

base_model = AutoModelForSeq2SeqLM.from_pretrained("./models/flan-t5-base-local", device_map="auto", trust_remote_code=True, dtype=torch.bfloat16)
fine_tuned_model = PeftModel.from_pretrained(
    base_model,
    "./models/flan-t5-base-totto-lora-finetuned"
)

tokenizer = AutoTokenizer.from_pretrained("./models/flan-t5-base-local")

fine_tuned_model.eval()
fine_tuned_model.cuda()

c:\Users\Youssef\Desktop\slm_fine_tune\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 282/282 [00:00<00:00, 2387.65it/s]
[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.
W0721 21:52:29.619000 16336 Lib\site-packages\torch\utils\flop_counter.py:29] triton not found; flop counting will not work for triton kernels

PeftModelForSeq2SeqLM(
  (base_model): LoraModel(
    (model): T5ForConditionalGeneration(
      (shared): Embedding(32128, 768)
      (encoder): T5Stack(
        (embed_tokens): Embedding(32128, 768)
        (block): ModuleList(
          (0): T5Block(
            (layer): ModuleList(
              (0): T5LayerSelfAttention(
                (SelfAttention): T5Attention(
                  (q): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (k): Linear(in_features=768, out_features=768, bias=False)
                  (v): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (o): Linear(in_features=768, out_features=768, bias=False)
                  (relative_attention_bias): Embedding(32, 12)
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (1): T5LayerFF(
                (DenseReluDense): T5DenseGatedActDense(
                  (wi_0): Linear(in_features=768, out_features=2048, bias=False)
                  (wi_1): Linear(in_features=768, out_features=2048, bias=False)
                  (wo): Linear(in_features=2048, out_features=768, bias=False)
                  (dropout): Dropout(p=0.1, inplace=False)
                  (act): NewGELUActivation()
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
          (1-11): 11 x T5Block(
            (layer): ModuleList(
              (0): T5LayerSelfAttention(
                (SelfAttention): T5Attention(
                  (q): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (k): Linear(in_features=768, out_features=768, bias=False)
                  (v): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (o): Linear(in_features=768, out_features=768, bias=False)
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (1): T5LayerFF(
                (DenseReluDense): T5DenseGatedActDense(
                  (wi_0): Linear(in_features=768, out_features=2048, bias=False)
                  (wi_1): Linear(in_features=768, out_features=2048, bias=False)
                  (wo): Linear(in_features=2048, out_features=768, bias=False)
                  (dropout): Dropout(p=0.1, inplace=False)
                  (act): NewGELUActivation()
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
        (final_layer_norm): T5LayerNorm()
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (decoder): T5Stack(
        (embed_tokens): Embedding(32128, 768)
        (block): ModuleList(
          (0): T5Block(
            (layer): ModuleList(
              (0): T5LayerSelfAttention(
                (SelfAttention): T5Attention(
                  (q): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (k): Linear(in_features=768, out_features=768, bias=False)
                  (v): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (o): Linear(in_features=768, out_features=768, bias=False)
                  (relative_attention_bias): Embedding(32, 12)
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (1): T5LayerCrossAttention(
                (EncDecAttention): T5Attention(
                  (q): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (k): Linear(in_features=768, out_features=768, bias=False)
                  (v): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (o): Linear(in_features=768, out_features=768, bias=False)
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (2): T5LayerFF(
                (DenseReluDense): T5DenseGatedActDense(
                  (wi_0): Linear(in_features=768, out_features=2048, bias=False)
                  (wi_1): Linear(in_features=768, out_features=2048, bias=False)
                  (wo): Linear(in_features=2048, out_features=768, bias=False)
                  (dropout): Dropout(p=0.1, inplace=False)
                  (act): NewGELUActivation()
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
          (1-11): 11 x T5Block(
            (layer): ModuleList(
              (0): T5LayerSelfAttention(
                (SelfAttention): T5Attention(
                  (q): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (k): Linear(in_features=768, out_features=768, bias=False)
                  (v): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (o): Linear(in_features=768, out_features=768, bias=False)
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (1): T5LayerCrossAttention(
                (EncDecAttention): T5Attention(
                  (q): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (k): Linear(in_features=768, out_features=768, bias=False)
                  (v): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (o): Linear(in_features=768, out_features=768, bias=False)
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (2): T5LayerFF(
                (DenseReluDense): T5DenseGatedActDense(
                  (wi_0): Linear(in_features=768, out_features=2048, bias=False)
                  (wi_1): Linear(in_features=768, out_features=2048, bias=False)
                  (wo): Linear(in_features=2048, out_features=768, bias=False)
                  (dropout): Dropout(p=0.1, inplace=False)
                  (act): NewGELUActivation()
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
        (final_layer_norm): T5LayerNorm()
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (lm_head): Linear(in_features=768, out_features=32128, bias=False)
    )
  )
)

### 10.2 Generate on Validation Set

In [2]:
from torch.utils.data import DataLoader

def generate_predictions(model, dataset, tokenizer, batch_size=96, max_new_tokens=64, num_beams=4):
    """Runs beam-search generation over `dataset` and returns (predictions, references)."""
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    predictions, references = [], []
    model.eval()

    for batch in loader:
        inputs = tokenizer(
            batch["prompt"],
            padding=True,
            truncation=True,
            max_length=384,
            return_tensors="pt",
        ).to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                num_beams=num_beams,
                do_sample=False,
            )

        preds = tokenizer.batch_decode(outputs, skip_special_tokens=True)
        predictions.extend(preds)
        references.extend(batch["target"])

    return predictions, references

In [5]:
ft_predictions, ft_references = generate_predictions(
    fine_tuned_model, dataset["validation"], tokenizer
)
print(f"Generated {len(ft_predictions)} predictions with the fine-tuned model.")

Generated 7700 predictions with the fine-tuned model.

In [7]:
# save the predictions and references to a jsonl file
import json
def save_predictions(predictions, references, path):
    with open(path, "w", encoding="utf-8") as f:
        for pred, ref in zip(predictions, references):
            f.write(json.dumps({"prediction": pred, "reference": ref}, ensure_ascii=False) + "\n")

# Save the predictions and references to a JSONL file
save_predictions(ft_predictions, ft_references, "totto_data/ft_predictions.jsonl")

In [7]:
import gc

# Free VRAM held by the fine-tuned model before loading a second full model
fine_tuned_model.to("cpu")
gc.collect()
torch.cuda.empty_cache()

base_model_for_eval = AutoModelForSeq2SeqLM.from_pretrained(
    "./models/flan-t5-base-local",
    device_map="auto",
    trust_remote_code=True,
    dtype=torch.bfloat16,
)
base_model_for_eval.eval()

base_predictions, base_references = generate_predictions(
    base_model_for_eval, dataset["validation"], tokenizer
)
print(f"Generated {len(base_predictions)} predictions with the base (non-fine-tuned) model.")

# References are identical for both models (same dataset, same order) 
assert base_references == ft_references

Loading weights: 100%|██████████| 282/282 [00:00<00:00, 1298.36it/s]
[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

Generated 7700 predictions with the base (non-fine-tuned) model.

In [8]:
import evaluate
import nltk

# METEOR needs these NLTK resources the first time it runs
nltk.download("wordnet", quiet=True)
nltk.download("omw-1.4", quiet=True)
nltk.download("punkt", quiet=True)
nltk.download("punkt_tab", quiet=True)

rouge_metric = evaluate.load("rouge")
bleu_metric = evaluate.load("bleu")
meteor_metric = evaluate.load("meteor")
bertscore_metric = evaluate.load("bertscore")

RUN_BLEURT = False
if RUN_BLEURT:

    bleurt_metric = evaluate.load("bleurt", module_type="metric", checkpoint="bleurt-large-512")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Youssef\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Youssef\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Youssef\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [9]:
def compute_all_metrics(predictions, references, label="model"):
    """Computes ROUGE-L, BLEU, METEOR, BERTScore-F1, and (optionally) BLEURT for one set
    of generated predictions against their references."""

    def sanitize(texts, placeholder="[empty]"):
        # bert_score (and some metric libs) crash or misbehave on empty/whitespace-only
        # strings depending on the installed transformers version. Empty generations are
        # also a real signal (esp. from a zero-shot base model giving up early) worth
        # counting rather than silently dropping.
        cleaned, n_empty = [], 0
        for t in texts:
            if t is None or t.strip() == "":
                cleaned.append(placeholder)
                n_empty += 1
            else:
                cleaned.append(t)
        return cleaned, n_empty

    predictions, n_empty_preds = sanitize(predictions)
    references, n_empty_refs = sanitize(references)
    if n_empty_preds or n_empty_refs:
        print(
            f"[{label}] sanitized {n_empty_preds} empty prediction(s) and "
            f"{n_empty_refs} empty reference(s) before scoring."
        )

    refs_list = [[r] for r in references]  # bleu/meteor expect a list of references per example

    rouge_res = rouge_metric.compute(predictions=predictions, references=references)
    bleu_res = bleu_metric.compute(predictions=predictions, references=refs_list)
    meteor_res = meteor_metric.compute(predictions=predictions, references=references)
    bertscore_res = bertscore_metric.compute(
        predictions=predictions, references=references, lang="en"
    )

    results = {
        "model": label,
        "ROUGE-L": rouge_res["rougeL"],
        "BLEU": bleu_res["bleu"],
        "METEOR": meteor_res["meteor"],
        "BERTScore-F1": sum(bertscore_res["f1"]) / len(bertscore_res["f1"]),
    }

    if RUN_BLEURT:
        bleurt_res = bleurt_metric.compute(predictions=predictions, references=references)
        results["BLEURT"] = sum(bleurt_res["scores"]) / len(bleurt_res["scores"])

    return results

In [10]:
import pandas as pd

base_results = compute_all_metrics(base_predictions, base_references, label="Base (no fine-tuning)")
ft_results = compute_all_metrics(ft_predictions, ft_references, label="Fine-tuned (LoRA)")

results_df = pd.DataFrame([base_results, ft_results]).set_index("model")
results_df

[Base (no fine-tuning)] sanitized 4 empty prediction(s) and 0 empty reference(s) before scoring.

Loading weights: 100%|██████████| 389/389 [00:00<00:00, 7620.49it/s]
[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[Fine-tuned (LoRA)] sanitized 4 empty prediction(s) and 0 empty reference(s) before scoring.

                        ROUGE-L      BLEU    METEOR  BERTScore-F1
model
Base (no fine-tuning)  0.191510  0.046260  0.210843      0.855862
Fine-tuned (LoRA)      0.376945  0.170677  0.400274      0.903236

In [9]:
import random

random.seed(67)
sample_indices = random.sample(range(len(ft_predictions)), 30)

for idx in sample_indices:
    example = dataset["validation"][idx]
    print(f"--- Example {idx} ---")
    print("Prompt (table + highlighted cells):\n", example["prompt"])
    print("\nReference target:", ft_references[idx])
    print("Model prediction :", ft_predictions[idx])
    print("=" * 80)

--- Example 612 ---
Prompt (table + highlighted cells):
 Task:
Generate a single factual sentence describing the information contained in the highlighted cells.
Use only information provided below.
Do not invent facts.
Page Title:
Mouche Phillips
Section Title:
Film
Highlighted Cells:
Row: 1, Column: 0
Row: 1, Column: 1
Row: 1, Column: 2
Table:
Year	Title	Role	Director
1986	Playing Beatie Bow	Beatie Bow	Donald Crombie
1993	Butterfly Island	Jackie Wilson	Frank Arnold
1997	Reprisal	Lavinia	Robert Marchand
1998	Never Tell Me Never	Meredith	David Elfick
Answer:


Reference target: Phillips began her career by starring as "Beatie Bow" in the 1986 film Playing Beatie Bow.
Model prediction : Mouche Phillips played Beatie Bow in the 1986 film Playing Beatie Bow.
================================================================================
--- Example 951 ---
Prompt (table + highlighted cells):
 Task:
Generate a single factual sentence describing the information contained in the highlighted cells.
Use only information provided below.
Do not invent facts.
Page Title:
Irish Mercantile Marine during World War II
Section Title:
Cargo
Highlighted Cells:
Row: 3, Column: 0
Row: 3, Column: 2
Row: 4, Column: 0
Row: 4, Column: 2
Table:
Land Area under Tillage

1911		1,697,338 acres (686,890 ha)
1916		1,735,000 acres (702,130 ha)
1918		2,383,000 acres (964,370 ha)
1921		1,807,843 acres (731,610 ha)
1932		1,424,000 acres (576,270 ha)
1939		1,492,000 acres (603,790 ha)
1941		2,235,413 acres (904,640 ha)
1944		2,567,000 acres (1,038,830 ha)
1951		1,717,283 acres (694,960 ha)
1961		1,598,700 acres (646,970 ha)
Chart illustrating how Irish agriculture responded to war-time demands of World War I and World War II
Answer:


Reference target: In 1916, there were 1,735,000 acres (702,130 ha) under plough and was increased to 2,383,000 acres (964,370 ha) in 1918.
Model prediction : The Irish Mercantile Marine in 1918 had 1,807,843 acres (731,610 ha) and 1,424,000 acres (576,270 ha).
================================================================================
--- Example 6275 ---
Prompt (table + highlighted cells):
 Task:
Generate a single factual sentence describing the information contained in the highlighted cells.
Use only information provided below.
Do not invent facts.
Page Title:
Gregory Harrison
Section Title:
Filmography
Highlighted Cells:
Row: 28, Column: 0
Row: 28, Column: 1
Row: 28, Column: 2
Table:
Feature films
Year	Title	Role	Notes
1973	The Harrad Experiment	Student	Film debut
1976	Jim the World's Greatest	Jim Nolan
1977	Fraternity Row	Zac Sterling
The Gathering	Bud Jr.
1984	Razorback	Carl Winters
1987	The Greatest Adventure: Stories from the Bible	Joseph (voice)	Direct-to-video (segment: "The Nativity")
North Shore	Chandler
1992	Body Chemistry II: The Voice of a Stranger	Dan
1993	Cadillac Girls	Sam
1994	Tis a Gift to Be Simple	Daniel Hanover	Short film
1995	Hard Evidence	Trent Turner
1996	It's My Party	Brandon Theis
1998	Air Bud: Golden Receiver	Dr. Patrick Sullivan	Alternative title: Air Bud 2
2000	Canone Inverso - Making Love	Jeno Piccolo	Alternative title: The Inverse Canon
2009	Love N' Dancing	Uncle Carl
Give 'Em Hell, Malone	Whitmore
2014	The M Word	Mack Riley
2016	Fair Haven	Dr. Gallagher
Television films/miniseries
Year	Title	Role	Notes
1975	Trilogy of Terror	Arthur Moore	Segment: "Julie"
1977	The Gathering	Bud Jr.
1978–79	Centennial	Levi Zendt	Miniseries
1979	The Best Place to Be	Rick Jawlosky
1980	The Women's Room	Ben Volper
Enola Gay: The Men, the Mission, the Atomic Bomb	Captain Bob Lewis
1981	For Ladies Only	John Phillips
1983	The Fighter	Merle Banks
The Hasty Heart	Sgt. Lachlen McLachlen
1985	Seduced	Mike Riordan
1986	Oceans of Fire	Ben Laforche
Picnic	Hal Carter
Fresno	Torch	Miniseries
1988	Hot Paint	Willie
Red River	Cherry Valance
1990	Dangerous Pursuit	Political Assassin
Angel of Death	Gary Nicholson
1991	Bare Essentials	William "Bill" Buzell
1992	Breaking the Silence	Paul Danner
Duplicates	Bob Boxletter
Split Images	Robbie Daniels
1993	Caught in the Act	Scott McNally
A Family Torn Apart	Tom Kelley	Alternative title: Sudden Fury
1994	Lies of the Heart: The Story of Laurie Kellogg	Bruce Kellogg
Mortal Fear	Philip Montgomery
A Christmas Romance	Brian Harding
1995	A Dangerous Affair	Robert Kenzer
Nothing Lasts Forever	Dr. Benjamin "Ben" Wallace
1996	Summer of Fear	Lucas Marshall
1997	When Secrets Kill	Greg Newhall
1998	Running Wild	Matt Robinson
Murder at 75 Birch	Rick Todson
1999	First Daughter	President Jonathan Hayes
Au Pair	Oliver Caldwell
2000	First Target	President Jonathan Hayes
2001	Au Pair II	Oliver Caldwell
2002	First Shot	President Jonathan Hayes
St. Sass	Adam Patrick
2009	Au Pair 3: Adventure in Paradise	Oliver Caldwell
Maneater	Teddy Alpert	Miniseries
2012	Undercover Bridesmaid	Mr. Thompson
2013	After All These Years	David Larabee
2014	The Nine Lives of Christmas	Chief Sam
2015	Cloudy with a Chance of Love	Grant
Signed, Sealed, Delivered: Truth Be Told	Joe O'Toole
2016	Signed, Sealed, Delivered: One in a Million	Joe O'Toole
Signed, Sealed, Delivered: Lost Without You	Joe O'Toole
My Christmas Love	Tom Manning
2017	Signed, Sealed, Delivered: Higher Ground	Joe O'Toole
Signed, Sealed, Delivered: Home Again	Joe O'Toole
2018	Signed, Sealed, Delivered: To the Altar	Joe O'Toole
Television series
Year	Title	Role	Notes
1976	Barnaby Jones	Ritchie Ridder	Episode: "Blood Vengeance"
M*A*S*H	Lt. Tony Baker	Episode: "The Nurses"
1977–78	Logan's Run	Logan 5	14 episodes
1979–86	Trapper John, M.D.	Dr. George Alonzo "Gonzo" Gates	142 episodes
1989–90	Falcon Crest	Michael Sharpe	22 episodes
1990–91	The Family Man	Jack Taylor	22 episodes
1995	500 Nations	Narrator (voice)	8 episodes
Sisters	Daniel Albright	5 episodes
Touched by an Angel	Pete Taylor	Episode: "There But for the Grace of God"
New York News	Jack Reilly	13 episodes
1996–97	Dark Skies	Old John Loengard (voice)	20 episodes (uncredited)
1998	Touched by an Angel	Richard	Episode: "Flights of Angels"
The Outer Limits	Dr. Larry Chambers	Episode: "To Tell the Truth"
Dead Man's Gun	Boucher / Trapper	Episode: "The Trapper"
Maggie Winters	Mr. Wiehe	Episode: "And Those Who Can't"
1999	Safe Harbor	Sheriff John Loring	10 episodes
2000	Ed	Nick Stanton	5 episodes
2000–01	Judging Amy	Tom Gillette	4 episodes
2002	Touched by an Angel	Don	Episode: "Forever Young"
2002–03	Strong Medicine	Dr. Randolf Kilner	4 episodes
2003	Miracles	Sheriff Ed Prescott	Episode: "The Bone Scatterer"
2005–06	Reunion	Russell Brewster	7 episodes
Joey	Dean	5 episodes
2006	Law & Order: Special Victims Unit	Nathan Speer	Episode: "Clock"
2008	Rodney	Duke Lewis	Episode: "Potty Mouth"
2009	Drop Dead Diva	Brandon Tharpe	Episode: "Crazy"
2009–11	One Tree Hill	Paul Norris	11 episodes
2010	CSI: NY	Roland Carson	Episode: "Out of the Sky"
2011	Hot in Cleveland	Dave	Episode: "Elka's Snowbird"
Body of Proof	Dr. Cameron Fischer	Episode: "Gross Anatomy"
2012	Outside the Box	Thorn	Episode: "Soylent Green"
Ringer	Tim Arbogast	5 episodes
2013	Psych	Ted Lomax	Episode: "Nip and Suck It"
2014	Reckless	Decatur "Dec" Fortnum	13 episodes
2015	Castle	Danny Valentine	Episode: "Dead from New York"
NCIS	Navy Capt. Roland Ebbakey	Episode: "Viral"
2015–16	Rizzoli & Isles	Ron Hanson	6 episodes
2017–18	Chesapeake Shores	Thomas O'Brien	9 episodes
2017	The Middle	Bennett Brooks	Episode: "Meet the Parents"
2018	American Housewife	Dan	Episode: "Highs and Lows"
Answer:


Reference target: Gregory Harrison appeared in a role as John Phillips in the 1981 movie For Ladies Only.
Model prediction : Gregory Harrison played the role of Sgt. Lachlen McLac in The Hasty Heart (1983).
================================================================================
--- Example 3345 ---
Prompt (table + highlighted cells):
 Task:
Generate a single factual sentence describing the information contained in the highlighted cells.
Use only information provided below.
Do not invent facts.
Page Title:
Nathaniel Stookey
Section Title:
Recordings
Highlighted Cells:
Row: 4, Column: 0
Row: 4, Column: 2
Row: 4, Column: 4
Table:
Album	Role	Librettist	Soloist(s)	Ensemble/Band	Conductor	Label	Release year
Music for Strings (1992-2002)	composer		Bonnie Thron, Brian Reagin, Rebekah Binford	North Carolina Symphony, Ciompi Quartet	William Henry Curry	Albany	2005
San Francisco Premieres	composer (Fling)			Left Coast Chamber Ensemble		Chamber Music Partnership	2005
The Bedlam in Goliath	contributor (Soothsayer)		Omar Rodríguez-López, Cedric Bixler-Zavala	The Mars Volta	Edwin Outwater	Universal/Motown	2008
The Composer is Dead	composer	Lemony Snicket	Lemony Snicket	San Francisco Symphony	Edwin Outwater	Harper Collins	2009
The Pursuit of Snappiness	composer (Nobody Suffers Like We Do)	Daniel Handler		Harvard Din & Tonics		Harvard Din & Tonics	2010
Junkestra	composer		David Weiss	San Francisco Symphony Youth Orchestra percussion section	Benjamin Shwartz	Innova Recordings	2010
O Compositor està Morto	composer	Lemony Snicket, trans. Assis	Fabio Goes	San Francisco Symphony	Edwin Outwater	Companhia das Letrinhas	2012
Le Compositeur est Mort	composer	Lemony Snicket, trans. Stookey/Matéo	Pépito Matéo	San Francisco Symphony	Edwin Outwater	Didier Jeunesse	2014
Zipperz	composer	Dan Harder	Manoel Felciano, Robin Coomer	Magik*Magik Orchestra	Donato Cabrera	Sh-K-Boom/Ghostlight	in press
Answer:


Reference target: San Francisco Symphony recorded The Composer is Dead with text by Lemony Snicket.
Model prediction : In 2005, Nathaniel Stookey collaborated with Omar Rodrguez-López, Cedric Bixler-Zavala in The Mars Volta.
================================================================================
--- Example 3830 ---
Prompt (table + highlighted cells):
 Task:
Generate a single factual sentence describing the information contained in the highlighted cells.
Use only information provided below.
Do not invent facts.
Page Title:
List of Kannada films of 1984
Additional Context:
The following is a list of films produced in the Kannada film industry in India in 1984, presented in alphabetical order.
Highlighted Cells:
Row: 57, Column: 0
Row: 57, Column: 1
Table:
Title	Director	Cast	Music	Reference
Aaradhane	Deepak Balraj	Vishnuvardhan, Geetha, K. S. Ashwath, Shivaram	Kumar
Accident	Shankar Nag	Shankar Nag, Ananth Nag, Arundhati Nag, Ramesh Bhat	Ilaiyaraaja
Amrutha Ghalige	Puttanna Kanagal	Sridhar, Ramakrishna, Padma Vasanthi	Vijaya Bhaskar
Anubhava	Kashinath	Kashinath, Abhinaya, Umashree, Dinesh	L. Vaidyanathan
Apoorva Sangama	Y. R. Swamy	Rajkumar, Shankar Nag, Ambika, Vajramuni	Upendra Kumar
Asha Kirana	B. N. Haridas	Shankar Nag, Geetha, Shamili, Sridhar	Satyam
Avala Antharanga	R. N. Jayagopal	Kalyan Kumar, Aarathi	M. Ranga Rao
Baddi Bangaramma	Kommineni	Srinath, Uma Shivakumar, Mahalakshmi, Bhavya, Ramakrishna, Jai Jagadish, Dinesh	K. Chakravarthy
Bandhana	Rajendra Singh Babu	Vishnuvardhan, Suhasini, Jai Jagadish, Roopa Devi, Dinesh	M. Ranga Rao
Bedaru Bombe	H. R. Bhargava	Shankar Nag, Jayamala, Roopa Chakravarthy	M. Ranga Rao
Benki Birugali	A. T. Raghu	Vishnuvardhan, Shankar Nag, Jayamala	M. Ranga Rao
Bekkina Kannu	S. N. Singh	Ramakrishna, Aarathi, Ramadevi, Musuri Krishnamurthy	Satyam
Chanakya	V. Somashekar	Vishnuvardhan, Madhavi, Vajramuni, Shivaram	Satyam
Devalaya	A. R. S. Devar	S. T. Gowdar, Sujata	R. Ratna
Eradu Rekhegalu	K. Balachander	Srinath, Saritha, Geetha, K. S. Ashwath, Charanraj, Lokanath	M. S. Viswanathan
Gajendra	V. Somashekar	Ambarish, Pavitra, Balakrishna	G. K. Venkatesh
Gandu Bherunda	Rajendra Singh Babu	Vajramuni, Amrish Puri, Ambarish, Srinath, Shankar Nag	Chellapilla Satyam
Guru Bhakti	K. N. Chandrashekar Sharma	Kalyan Kumar, B. Saroja Devi, Ambarish, Jayamalini	G. K. Venkatesh
Hennina Sowbhagya	T. V. Panchakshari	Lokesh, Ashok, Aarathi, Geetha	Upendra Kumar
Hosa Itihaasa	D. Rajendra Babu	Tiger Prabhakar, Jayamala, Vajramuni, Mukhyamantri Chandru	Sankar Ganesh
Huli Hejje	Ravee	Vishnuvardhan, Vijayalakshmi Singh, Tiger Prabhakar	Vijaya Bhaskar
Indina Bharatha	T. Krishna	Shankar Nag, Ambika, Shashikala, Mukhyamantri Chandru	K. Chakravarthy
Indina Ramayana	Raja Chandra	Vishnuvardhan, Gayathri, Tulasi, Leelavathi, Sridhar	Vijay Anand
Jiddu	D. Rajendra Babu	Tiger Prabhakar, Jayamala, T. N. Balakrishna	G. K. Venkatesh
Kalinga Sarpa	D. Rajendra Babu	Shankar Nag, Manjula, Vajramuni, Thoogudeepa Srinivas	Rajan-Nagendra
Kaliyuga	Raja Chandra	Rajesh, Aarathi, Dinesh	G. K. Venkatesh
Khaidi	K. S. R. Das	Vishnuvardhan, Madhavi, Aarathi, Dheerendra Gopal	K. Chakravarthy
Madhuve Madu Tamashe Nodu	S. A. Chandrasekhar	Vishnuvardhan, Aarathi, Mahalakshmi, Dwarakish	Vijay Anand
Makkaliralavva Mane Thumba	T. S. Nagabharana	Ananth Nag, Lakshmi, Shankar Nag, Gayathri, Ramesh Bhat	G. K. Venkatesh
Male Banthu Male	P. S. Prakash	Arjun Sarja, Kumari Indira, K. S. Ashwath	G. K. Venkatesh
Marali Goodige	K. R. Shantaram	Kalyan Kumar, Roopa	Rajan Nagendra
Masanada Hoovu	Puttanna Kanagal	Ambarish, Jayanthi, Aparna	Vijaya Bhaskar
Mooru Janma	H. R. Bhargava	Ambarish, Ambika, Anuradha	Rajan-Nagendra
Mrugaalaya	V. Somashekar	Ambarish, Geetha, Sudheer, Sundar Krishna Urs	Rajan-Nagendra
Naane Raja	C. V. Rajendran	V. Ravichandran, Jai Jagadish, Ambarish, Ambika, M. P. Shankar	Sankar Ganesh
Nagabekamma Nagabeku	B. Subba Rao	Shankar Nag, Jayamala, Tulasi, Kalyan Kumar, Ramakrishna	Satyam
Nagara Mahime	Kallesh	Sundar Krishna Urs, Sripriya, Master Sanjay, Dinesh	Ilayaraaja
Olave Baduku	K. V. Jayaram	Ananth Nag, Gayathri, Lokanath	M. Ranga Rao
Olavu Moodidaga	B. Mallesh	Ananth Nag, Lakshmi, Ramakrishna, Dinesh, Leelavathi	Rajan-Nagendra
Onde Rakhta	Sreekumaran Thampi	Ambarish, Ambika, Sundar Krishna Urs, Mukhyamantri Chandru, Pandari Bai	Rajan-Nagendra
Onti Dhwani	T. S. Nagabharana	Ambarish, Jayamala, Lokesh, Manjula	Upendra Kumar
Pavitra Prema	A. V. Sheshagiri Rao	Shankar Nag, Aarathi, Roopa Devi, Srinivasa Murthy	Vijaya Bhaskar
Police Papanna	Dasari Narayana Rao	Dwarakish, Udayakumar, Kalyan Kumar, Rani Sudha, Jayamalini	J. V. Raghavulu
Pooja Phala	Dhananjaya	Srinath, Aarathi, Arjun Sarja, Mahalakshmi	Satyam
Prachanda Kulla	Prakash P. S	Dwarakish, Vishnuvardhan, Raadhika, Silk Smitha	Vijaya Bhaskar
Pralayanthaka	B. Subba Rao	V. Ravichandran, Bhavya, Jai Jagadish, Mukhyamantri Chandru	Sankar Ganesh
Preethi Vathsalya	H. R. Bhargava	Srinath, Aarathi, Tiger Prabhakar	Rajan-Nagendra
Prema Sakshi	B. Mallesh	Ananth Nag, Sujatha, Poornima	Rajan-Nagendra
Premave Balina Belaku	A. V. Sheshagiri Rao	Ananth Nag, Aarathi, Jayamala, Srinivasa Murthy	M. Ranga Rao
Premigala Saval	V. Somashekar	V. Ravichandran, Tiger Prabhakar, Archana	Rajan-Nagendra
Raktha Tilaka	Joe Simon	Shankar Nag, Jayamala, Tiger Prabhakar, Kanchana	Satyam
Ramapurada Ravana	Raja Chandra	Ananth Nag, Aarathi, Geetha	Upendra Kumar
Ravi Moodi Banda	Rangachar	Chandrashekar, Jai Jagadish, Sumithra	Mysore Mohan
Rudranaga	Mani Murugan	Vishnuvardhan, R. N. Sudarshan, Madhavi, Balakrishna	M. Ranga Rao
Runamukthalu	Puttanna Kanagal	Bharathi Vishnuvardhan, Ramakrishna, Sundar Krishna Urs, Padma Vasanthi	Vijaya Bhaskar
Samayada Gombe	Dorai-Bhagwan	Rajkumar, Roopa Devi, Menaka, Shashikala, Kanchana	M. Ranga Rao
Shapatha	Amrutham	Shankar Nag, Nalini, Ashok	Sankar Ganesh
Shiva Kanye	Hunsur Krishnamurthy	Ramakrishna, Madhavi, Roopadevi	T. G. Lingappa
Shravana Banthu	Singeetham Srinivasa Rao	Rajkumar, Srinath, Urvashi, K. S. Ashwath	M. Ranga Rao
Shrungara Maasa	Pattabhirama Reddy	Amol Palekar, Deepa Dhanraj	Rajeev Taranath
Sidilu	B. Subba Rao	Ambarish, Geetha, Malathi, Srinath	Satyam
Sukha Samsarakke 12 Sutragalu	Raja Chandra	Ananth Nag, Gayathri, C. R. Simha	K. Chakravarthy
Thaliya Bhagya	Vijay	Shankar Nag, Charanraj, Lakshmi, Vajramuni	Satyam
Yarivanu	Dorai-Bhagwan	Rajkumar, Roopa Devi, Master Lohith, B. Saroja Devi, Srinath	Rajan-Nagendra
Answer:


Reference target: Shapatha is a 1984 Indian Kannada film, directed by Amrutham.
Model prediction : Bhavana is a 1984 Kannada film directed by Rajkumar.
================================================================================
--- Example 3402 ---
Prompt (table + highlighted cells):
 Task:
Generate a single factual sentence describing the information contained in the highlighted cells.
Use only information provided below.
Do not invent facts.
Page Title:
Davidson Township, Sullivan County, Pennsylvania
Section Title:
Demographics
Additional Context:
As of the census of 2000, there were 626 people, 269 households, and 189 families residing in the township. The population density was 8.0 people per square mile (3.1/km²).
Highlighted Cells:
Row: 2, Column: 0
Row: 2, Column: 1
Table:
Historical population
Census	Pop.		%±
2010	573		—
Est. 2016	539		−5.9%
U.S. Decennial Census
Answer:


Reference target: The population was 573, at the 2010 census.
Model prediction : As of the census of 2010, there were 573 people residing in Davidson Township.
================================================================================
--- Example 2186 ---
Prompt (table + highlighted cells):
 Task:
Generate a single factual sentence describing the information contained in the highlighted cells.
Use only information provided below.
Do not invent facts.
Page Title:
Gage Gubrud
Section Title:
College statistics
Highlighted Cells:
Row: 5, Column: 0
Row: 5, Column: 6
Row: 5, Column: 8
Table:
NCAA Collegiate Career Stats
Eastern Washington Eagles
Season	Games	Games Started	Record	Passing	Rushing
Comp	Att	Yards	Pct.	TD	Int	Passer Rating	Att	Yards	Avg	TD
2015	4	0	0–0	7	13	66	53.8	0	1	81.1	12	31	2.6	1
2016	14	14	12–2	386	570	5,160	67.7	48	14	166.6	134	606	4.5	5
2017	10	10	6–4	261	422	3,342	61.8	26	12	143.0	82	236	2.9	5
NCAA Career Totals	28	24	18–6	654	1,005	8,568	61.1	74	27	130.2	228	873	3.3	11
Answer:


Reference target: Gage Gubrud finished 2016 with a single-season record of 5,160 passing yards and 48 touchdowns.
Model prediction : Gage Gubrud finished the 2017 season with a record of 6–4 with 261 rushing yards.
================================================================================
--- Example 4885 ---
Prompt (table + highlighted cells):
 Task:
Generate a single factual sentence describing the information contained in the highlighted cells.
Use only information provided below.
Do not invent facts.
Page Title:
List of Bones characters
Section Title:
Interns
Additional Context:
Since the departure of Dr. Zack Addy from the Jeffersonian, Dr.
Highlighted Cells:
Row: 4, Column: 0
Row: 4, Column: 1
Row: 4, Column: 2
Table:
Actor	Character	Seasons
Eugene Byrd	Clark Edison	3–12
Ryan Cartwright	Vincent Nigel-Murray	4–6
Michael Grant Terry	Wendell Bray	4–12
Joel David Moore	Colin Fisher	4–9, 11–12
Pej Vahdat	Arastoo Vaziri	4–12
Carla Gallo	Daisy Wick	4–12
Scott Lowell	Douglas Filmore	6, 9
Luke Kleintank	Finn Abernathy	7–9
Brian Klugman	Oliver Wells	8–11
Ignacio Serricchio	Rodolfo Fuentes	9–12
Laura Spencer	Jessica Warren	9–12
Answer:


Reference target: Intern Joel David Moore portrayed as Dr. Colin Fisher (seasons 4–9, 11–12).
Model prediction : Carla Gallo played the role of Arastoo Vaziri.
================================================================================
--- Example 3518 ---
Prompt (table + highlighted cells):
 Task:
Generate a single factual sentence describing the information contained in the highlighted cells.
Use only information provided below.
Do not invent facts.
Page Title:
2008–09 Clemson Tigers men's basketball team
Section Title:
Player statistics
Additional Context:
Finals Stats
Highlighted Cells:
Row: 16, Column: 3
Table:
#	Name	GP	GS	Min	FG%	3PT%	FT%	R/G	A/G	STL	BLK	PTS/G
35	Booker, Trevor	32	32	30.7	.571	.409	.707	9.7	1.7	47	63	15.3
01	Rivers, K. C.	32	32	31.0	.449	.392	.667	6.0	1.6	55	14	14.2
22	Oglesby, Terrence	32	31	25.8	.375	.388	.845	1.7	1.8	28	1	13.2
02	Stitt, Demontez	32	32	25.9	.413	.273	.673	2.4	3.8	48	14	8.7
12	Sykes, Raymond	32	31	21.7	.578	.000	.557	5.1	0.7	20	32	7.9
15	Potter, David	32	0	17.6	.380	.365	.756	2.2	1.3	19	7	4.9
45	Grant, Jerai	32	1	14.6	.644	.000	.647	3.2	0.5	12	45	4.7
11	Young, Andre	32	0	14.9	.377	.390	.632	0.8	2.1	31	1	4.4
05	Smith, Tanner	32	0	13.2	.448	.357	.667	1.8	1.1	29	6	3.6

**Interpretation:** 
All four completed metrics point the same direction: fine-tuning clearly improved the model. ROUGE-L nearly doubled (0.201 -> 0.378), METEOR nearly doubled (0.203 -> 0.392), and BLEU almost tripled (0.060 -> 0.167), showing the fine-tuned model produces text much closer in wording and structure to the reference summaries. BERTScore-F1 rose more modestly (0.860 -> 0.903) because it measures semantic similarity, and even the base model's off-task output is topically related enough to score reasonably well on that scale — so the small BERTScore gap combined with the large BLEU gap together indicate the base model is "fluent but off-task," while the fine-tuned model is both fluent and on-task. The 2 vs. 4 empty predictions are negligible noise at this sample size and don't affect the conclusion.