# QLoRA Fine-Tuning FLAN-T5-base for Table-to-Text Summarization (ToTTo)

**Goal:** fine-tune `google/flan-t5-base` with quantized LoRA to generate a single factual sentence
summarizing the highlighted cells of a Wikipedia table (ToTTo dataset).

**Pipeline:** raw ToTTo JSON -> prompt/target pairs -> tokenization ->Quantization -> LoRA fine-tuning -> save adapter -> inference & evaluation.

**Hardware:** local RTX 3060 (12GB VRAM), Ryzen 7 5600X, 32GB RAM - all training done on-device, no cloud.

## 1. Environment Setup

Confirm CUDA / GPU availability before doing anything expensive.

In [1]:
# GPU setup
import torch

# Check CUDA availability and GPU properties
print(f"torch version: {torch.__version__}")
print(f"CUDA version: {torch.version.cuda}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"GPU count: {torch.cuda.device_count()}")

if torch.cuda.is_available():
    print(f"GPU name: {torch.cuda.get_device_name(0)}")
    print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

torch version: 2.11.0+cu128
CUDA version: 12.8
CUDA available: True
GPU count: 1
GPU name: NVIDIA GeForce RTX 3060
VRAM: 12.9 GB

## 2. Base Model & Tokenizer Loading

In [ ]:
# Load the model and tokenizer
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, BitsAndBytesConfig
import torch
save_directory = "./models/flan-t5-base-local"

# Define the quantization configuration for 4-bit quantization
bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,                     # Enable 4-bit quantization
        bnb_4bit_quant_type="nf4",             # Use NF4 quantization type
        bnb_4bit_compute_dtype=torch.bfloat16, # Compute in bfloat16 for stability
        bnb_4bit_use_double_quant=True,        # Nested quantization for extra savings
    )
# Load from local directory
tokenizer = AutoTokenizer.from_pretrained(save_directory, local_files_only=True)
model = AutoModelForSeq2SeqLM.from_pretrained(
    save_directory,
    quantization_config=bnb_config,   # 4 bit quantization will be used in qlora
    device_map="auto",           # Automatically place model layers
    trust_remote_code=True,      # Required for some models
    dtype=torch.bfloat16,        # Use bfloat16 for non-quantized parts
)

c:\Users\Youssef\Desktop\slm_fine_tune\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
W0714 22:36:46.857000 2976 Lib\site-packages\torch\utils\flop_counter.py:29] triton not found; flop counting will not work for triton kernels
Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]c:\Users\Youssef\Desktop\slm_fine_tune\.venv\Lib\site-packages\bitsandbytes\backends\cuda\ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Loading weights: 100%|██████████| 282/282 [00:01<00:00, 269.10it/s]
[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

## 3. Dataset Loading & Tokenization

In [4]:
# Load the prompt datasets
from datasets import load_dataset

dataset = load_dataset(
    "json",
    data_files={
        "train": "totto_data/train.jsonl",
        "validation": "totto_data/validation.jsonl"
    }
)

print(dataset["train"][0])
print(dataset["validation"][0])

{'id': 1762238357686640028, 'prompt': 'Task:\nGenerate a single factual sentence describing the information contained in the highlighted cells.\nUse only information provided below.\nDo not invent facts.\nPage Title:\nList of 8/9 PM telenovelas of Rede Globo\nSection Title:\n2000s\nHighlighted Cells:\nRow: 13, Column: 2\nTable:\n#\tRun\tTitle\tChapters\tAuthor\tDirector\tIbope Rating\n59\tJune 5, 2000— February 2, 2001\tLaços de Família\t209\tManoel Carlos\tRicardo Waddington\t44.9\n60\tFebruary 5, 2001— September 28, 2001\tPorto dos Milagres\t203\tAguinaldo Silva Ricardo Linhares\tMarcos Paulo Simões\t44.6\n61\tOctober 1, 2001— June 14, 2002\tO Clone\t221\tGlória Perez\tJayme Monjardim\t47.0\n62\tJune 17, 2002— February 14, 2003\tEsperança\t209\tBenedito Ruy Barbosa\tLuiz Fernando\t37.7\n63\tFebruary 17, 2003— October 10, 2003\tMulheres Apaixonadas\t203\tManoel Carlos\tRicardo Waddington\t46.6\n64\tOctober 13, 2003— June 25, 2004\tCelebridade\t221\tGilberto Braga\tDennis Carvalho\t46.0\n65\tJune 28, 2004— March 11, 2005\tSenhora do Destino\t221\tAguinaldo Silva\tWolf Maya\t50.4\n66\tMarch 14, 2005— November 4, 2005\tAmérica\t203\tGlória Perez\tJayme Monjardim Marcos Schechtman\t49.4\n67\tNovember 7, 2005— July 7, 2006\tBelíssima\t209\tSílvio de Abreu\tDenise Saraceni\t48.5\n68\tJuly 10, 2006— March 2, 2007\tPáginas da Vida\t203\tManoel Carlos\tJayme Monjardim\t46.8\n69\tMarch 5, 2007— September 28, 2007\tParaíso Tropical\t179\tGilberto Braga Ricardo Linhares\tDennis Carvalho\t42.8\n70\tOctober 1, 2007— May 31, 2008\tDuas Caras\t210\tAguinaldo Silva\tWolf Maya\t41.1\n71\tJune 2, 2008— January 16, 2009\tA Favorita\t197\tJoão Emanuel Carneiro\tRicardo Waddington\t39.5\n72\tJanuary 19, 2009— September 11, 2009\tCaminho das Índias\t203\tGlória Perez\tMarcos Schechtman\t38.8\n73\tSeptember 14, 2009— May 14, 2010\tViver a Vida\t209\tManoel Carlos\tJayme Monjardim\t35.6\nAnswer:\n', 'target': 'A Favorita is the telenovela aired in the 9 pm timeslot.'}
{'id': 7391450717765563190, 'prompt': 'Task:\nGenerate a single factual sentence describing the information contained in the highlighted cells.\nUse only information provided below.\nDo not invent facts.\nPage Title:\nList of Governors of South Carolina\nSection Title:\nGovernors under the Constitution of 1868\nAdditional Context:\nParties Democratic Republican\nHighlighted Cells:\nRow: 3, Column: 0\nRow: 3, Column: 2\nRow: 3, Column: 3\nTable:\n#\tGovernor\tTook Office\tLeft Office\tLt. Governor\tParty\tNotes\n74\t-\tRobert Kingston Scott\tJuly 6, 1868\tDecember 7, 1872\tLemuel Boozer Alonzo J. Ransier\tRepublican\t\n75\t-\tFranklin J. Moses, Jr.\tDecember 7, 1872\tDecember 1, 1874\tRichard Howell Gleaves\tRepublican\t\n76\t-\tDaniel Henry Chamberlain\tDecember 1, 1874\tDecember 14, 1876\tRichard Howell Gleaves\tRepublican\tClaimed Governorship after 1876 election\n77\t-\tWade Hampton III\tDecember 14, 1876\tFebruary 26, 1879\tWilliam Dunlap Simpson\tDemocratic\tResigned\n78\t-\tWilliam Dunlap Simpson\tFebruary 26, 1879\tSeptember 1, 1880\tJohn D. Kennedy\tDemocratic\tNot elected\n79\t-\tThomas Bothwell Jeter\tSeptember 1, 1880\tNovember 30, 1880\tvacant\tDemocratic\t\n80\t-\tJohnson Hagood\tNovember 30, 1880\tDecember 1, 1882\tJohn D. Kennedy\tDemocratic\t\n81\t-\tHugh Smith Thompson\tDecember 1, 1882\tJuly 10, 1886\tJohn Calhoun Sheppard\tDemocratic\tResigned\n82\t-\tJohn Calhoun Sheppard\tJuly 10, 1886\tNovember 30, 1886\tvacant\tDemocratic\tNot elected\n83\t-\tJohn Peter Richardson III\tNovember 30, 1886\tDecember 4, 1890\tWilliam Mauldin\tDemocratic\t\n84\t-\tBenjamin Ryan Tillman\tDecember 4, 1890\tDecember 4, 1894\tEugene Gary W.H. Timmerman\tDemocratic\t\n85\t-\tJohn Gary Evans\tDecember 4, 1894\tJanuary 18, 1897\tW.H. Timmerman\tDemocratic\t\nAnswer:\n', 'target': 'Daniel Henry Chamberlain was the 76th Governor of South Carolina from 1874.'}

In [12]:
def preprocess(examples):
    model_inputs = tokenizer(
        examples["prompt"],
        max_length=384,
        truncation=True,
    )

    labels = tokenizer(
        text_target=examples["target"],
        max_length=64,
        truncation=True,
    )

    model_inputs["labels"] = labels["input_ids"]

    return model_inputs

In [13]:
tokenized_dataset = dataset.map(
    preprocess,
    batched=True,
    remove_columns=dataset["train"].column_names
)

In [6]:
# Sanity check: print the first tokenized example
print(tokenized_dataset["train"][0])
print(tokenized_dataset["validation"][0])
# print stats 
print(f"Number of training samples: {len(tokenized_dataset['train'])}")
print(f"Number of validation samples: {len(tokenized_dataset['validation'])}")

{'input_ids': [16107, 10, 6939, 2206, 3, 9, 712, 685, 3471, 7142, 3, 16012, 8, 251, 6966, 16, 8, 12566, 2640, 5, 2048, 163, 251, 937, 666, 5, 531, 59, 16, 2169, 6688, 5, 5545, 11029, 10, 6792, 13, 505, 87, 1298, 3246, 3, 1931, 5326, 15, 521, 7, 13, 1624, 15, 9840, 115, 32, 5568, 11029, 10, 2766, 7, 16388, 15, 26, 7845, 7, 10, 11768, 10, 10670, 29926, 10, 204, 4398, 10, 1713, 7113, 11029, 8647, 7, 10236, 2578, 27, 115, 32, 855, 21662, 3, 3390, 1515, 7836, 2766, 318, 2083, 3547, 4402, 325, 24065, 7, 20, 1699, 51, 2, 40, 23, 9, 460, 1298, 1140, 32, 15, 40, 19783, 2403, 6043, 32, 3129, 30557, 314, 27336, 1640, 2083, 7836, 4402, 318, 1600, 13719, 4402, 3625, 32, 103, 7, 8573, 9, 11176, 3, 23330, 71, 17996, 138, 26, 32, 26551, 2403, 6043, 32, 6741, 3272, 15, 7, 16902, 7, 1838, 32, 6619, 2, 15, 7, 314, 25652, 3, 4241, 1797, 1914, 4402, 318, 1515, 11363, 4407, 411, 4779, 782, 204, 2658, 350, 40, 4922, 52, 23, 9, 1915, 457, 9373, 526, 2963, 5670, 26, 603, 314, 26346, 3, 4056, 1515, 12864, 4407, 318, 2083, 11363, 3888, 1122, 883, 152, 11666, 460, 1298, 2798, 11272, 32, 2770, 63, 11038, 32, 7, 9, 2318, 23, 172, 28989, 6862, 5, 940, 3, 3891, 2083, 12864, 3888, 318, 1797, 10372, 3888, 10094, 88, 60, 7, 5085, 9, 2407, 32, 18089, 7, 3, 23330, 1140, 32, 15, 40, 19783, 2403, 6043, 32, 3129, 30557, 314, 28833, 6687, 1797, 10670, 3888, 318, 1515, 14105, 4406, 26071, 15644, 15, 204, 2658, 24378, 32, 3497, 122, 9, 18563, 1184, 2165, 107, 32, 314, 22642, 7123, 1515, 13719, 4406, 318, 1332, 9694, 3105, 4892, 21783, 103, 19344, 32, 204, 2658, 71, 17996, 138, 26, 32, 26551, 9091, 932, 9, 305, 22776, 3, 3539, 1332, 11363, 3105, 318, 1671, 6464, 3105, 736, 5134, 658, 3, 23330, 350, 40, 4922, 52, 23, 9, 1915, 457, 9373, 526, 2963, 5670, 26, 603, 16902, 7, 1880, 12041, 348, 9526, 5, 591, 3, 3708, 1671, 7973, 3105, 318, 1718, 7973, 3581, 5622, 2, 7, 7, 603, 9, 460, 1298, 180, 2, 40, 2099, 32, 20, 891, 60, 76, 3128, 159, 15, 12969, 18778, 314, 19253, 3, 3651, 1718, 10372, 3581, 318, 1332, 3547, 4101, 276, 2975, 19604, 7, 836, 19575, 9, 3, 23330, 1140, 32, 15, 40, 19783, 9373, 526, 2963, 5670, 26, 603, 9668, 5, 927, 3, 3951, 1332, 7836, 4101, 318, 1600, 13719, 4101, 4734, 2, 7, 32, 28907, 3, 26593, 24378, 32, 3497, 122, 9, 2403, 6043, 32, 6741, 3272, 15, 7, 18563, 1184, 2165, 107, 32, 314, 19419, 2861, 1797, 1914, 4101, 318, 932, 12074, 2628, 970, 9, 7, 1184, 9, 7, 3, 15239, 71, 17996, 138, 26, 32, 26551, 9091, 932, 9, 314, 11039, 3, 4450, 1515, 3547, 2628, 318, 1762, 11940, 2464, 71, 16717, 155, 9, 3, 27181, 2194, 2, 32, 262, 348, 76, 15, 40, 1184, 29, 21810, 2403, 6043, 32, 3129, 30557, 220, 22321, 9455, 1762, 12370, 2464, 318, 1600, 9694, 2464, 5184, 23738, 211, 3, 2, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [71, 16717, 155, 9, 19, 8, 3, 1931, 5326, 15, 521, 3, 2378, 26, 16, 8, 668, 6366, 648, 3171, 5, 1]}
{'input_ids': [16107, 10, 6939, 2206, 3, 9, 712, 685, 3471, 7142, 3, 16012, 8, 251, 6966, 16, 8, 12566, 2640, 5, 2048, 163, 251, 937, 666, 5, 531, 59, 16, 2169, 6688, 5, 5545, 11029, 10, 6792, 13, 10510, 7, 13, 1013, 5089, 5568, 11029, 10, 10510, 7, 365, 8, 11378, 13, 507, 3651, 11180, 1193, 6327, 10, 17450, 7, 10021, 8994, 16388, 15, 26, 7845, 7, 10, 11768, 10, 6180, 29926, 10, 3, 632, 11768, 10, 6180, 29926, 10, 204, 11768, 10, 6180, 29926, 10, 220, 4398, 10, 1713, 10510, 304, 1825, 2126, 14298, 2126, 301, 17, 5, 10510, 3450, 2507, 7, 3, 4581, 3, 18, 2715, 26133, 4972, 1718, 8580, 507, 3651, 1882, 7973, 507, 5865, 312, 51, 76, 15, 40, 1491, 32, 2558, 901, 32, 20547, 446, 5, 15039, 7, 972, 8994, 6374, 3, 18, 16079, 446, 5, 20064, 6, 8206, 5, 1882, 7973, 507, 5865, 1882, 1914, 507, 4581, 4117, 571, 3820, 350, 109, 16001, 8994, 3, 3959, 3, 18, 4173, 7780, 9572, 521, 77, 1882, 1914, 507, 4581, 1882, 11363, 507, 3959, 4117, 571, 3820, 350, 109, 16001, 8994, 4779, 8287, 10510, 2009, 227, 507, 3959, 4356, 3, 4013, 3, 18, 26765, 24341, 6289, 1882, 11363, 507, 3959, 2083, 13597, 507, 4440, 4599, 6393, 8478, 21965, 10021, 419, 15532, 3, 3940, 3, 18, 4599, 6393, 8478, 21965, 2083, 13597, 507, 4440, 1600, 1914, 507, 2079, 1079, 309, 5, 14532, 10021, 933, 8160, 3, 4440, 3, 18, 3576, 2867, 2091, 1022, 449, 1600, 1914, 507, 2079, 1671, 11558, 507, 2079, 14333, 10021, 2775, 3, 18, 5891, 1626, 10452, 1671, 11558, 507, 2079, 1882, 1914, 507, 4613, 1079, 309, 5, 14532, 10021, 3, 4959, 3, 18, 11560, 107, 3931, 14653, 1882, 1914, 507, 4613, 1718, 10372, 507, 3840, 1079, 3104, 9492, 29, 451, 1572, 986, 10021, 419, 15532, 3, 4613, 3, 18, 1079, 3104, 9492, 29, 451, 1572, 986, 1718, 10372, 507, 3840, 1671, 11558, 507, 3840, 14333, 10021, 933, 8160, 3, 4591, 3, 18, 1079, 2737, 4117, 739, 6289, 1671, 11558, 507, 3840, 1882, 6464, 507, 2394, 4599, 1534, 83, 2644, 10021, 3, 4608, 3, 18, 15717, 7826, 22067, 348, 1882, 6464, 507, 2394, 1882, 6464, 507, 4240, 18281, 15, 13439, 549, 5, 566, 5, 332, 12174, 348, 10021, 11989, 3, 18, 1079, 13439, 18305, 1882, 6464, 507, 4240, 1762, 14985, 507, 4327, 549, 5, 566, 5, 332, 12174, 348, 10021, 11801, 10, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [4173, 7780, 9572, 521, 77, 47, 8, 3, 3959, 189, 10510, 13, 1013, 5089, 45, 507, 4581, 5, 1]}
Number of training samples: 120761
Number of validation samples: 7700

## 4. QLoRA Configuration

In [7]:
# LoRA configuration
from peft import LoraConfig, TaskType, get_peft_model
peft_config = LoraConfig(
    r=8,                                # Rank of the low-rank matrices
    lora_alpha=16,                      # Scaling factor for the low-rank matrices
    target_modules=["q", "v"],          # Target modules for LoRA
    lora_dropout=0.1,                   # Dropout rate for LoRA layers
    bias="none",                        # No bias in LoRA layers
    task_type=TaskType.SEQ_2_SEQ_LM,    # Task type for encoder-decoder models
    )

model = get_peft_model(model, peft_config)

In [8]:
model.print_trainable_parameters()

trainable params: 884,736 || all params: 248,462,592 || trainable%: 0.3561

## 5. Training Configuration & Sanity Checks
### 5.1 Trainer Setup

In [23]:
import os
from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments, EarlyStoppingCallback, DataCollatorForSeq2Seq
os.environ["TENSORBOARD_LOGGING_DIR"] = "./logs"

training_args = Seq2SeqTrainingArguments(
    output_dir="./results",

    # Training
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    gradient_accumulation_steps=1,
    gradient_checkpointing=False,
    learning_rate=1e-4,
    weight_decay=0.01,
    warmup_steps=500,
    lr_scheduler_type="cosine",

    # Logging
    logging_steps=1,
    save_steps=1000,
    eval_steps=500,
    eval_strategy="epoch",
    save_strategy="epoch",
    train_sampling_strategy="group_by_length",
    logging_first_step=True,   
    logging_nan_inf_filter=False,

    # Generation
    predict_with_generate=False,
    generation_max_length=32,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    # Mixed precision
    fp16=False,
    bf16=True, 

    # Optimizer
    optim="adamw_torch", 

    seed=67,        # Set a random seed for reproducibility

    report_to="tensorboard",
)


data_collator = DataCollatorForSeq2Seq(
    tokenizer,
    model=model,
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    processing_class=tokenizer,
    data_collator=data_collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

### 5.2 Pre-Training Sanity Check

Before committing to a full training run, confirm the pipeline produces a finite, reasonable loss on an untouched batch.

In [10]:
model.eval()
batch = next(iter(trainer.get_train_dataloader()))
batch = {k: v.to(model.device) for k, v in batch.items()}
with torch.no_grad():
    out = model(**batch)
print("loss on a fresh, untrained batch:", out.loss)

loss on a fresh, untrained batch: tensor(2.4219, device='cuda:0', dtype=torch.bfloat16)

## 6. Fine-Tuning

In [24]:
trainer.train()

TrainOutput(global_step=22644, training_loss=1.8212749656514216, metrics={'train_runtime': 10294.7161, 'train_samples_per_second': 35.191, 'train_steps_per_second': 2.2, 'total_flos': 1.4621934698984448e+17, 'train_loss': 1.8212749656514216, 'epoch': 3.0})

In [25]:
# Save the fine-tuned model
model.save_pretrained("./models/flan-t5-base-totto-qlora-finetuned")

## 7. Evaluation & Inference
### 7.1 Reload Base Model + QLoRA Adapter

In [1]:
from peft import PeftModel
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
import torch

base_model = AutoModelForSeq2SeqLM.from_pretrained("./models/flan-t5-base-local", device_map="auto", trust_remote_code=True, dtype=torch.bfloat16)
fine_tuned_model = PeftModel.from_pretrained(
    base_model,
    "./models/flan-t5-base-totto-qlora-finetuned"
)

tokenizer = AutoTokenizer.from_pretrained("./models/flan-t5-base-local")

fine_tuned_model.eval()
fine_tuned_model.cuda()

c:\Users\Youssef\Desktop\slm_fine_tune\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 282/282 [00:00<00:00, 2150.73it/s]
[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.
W0715 02:08:06.779000 3888 Lib\site-packages\torch\utils\flop_counter.py:29] triton not found; flop counting will not work for triton kernels

PeftModelForSeq2SeqLM(
  (base_model): LoraModel(
    (model): T5ForConditionalGeneration(
      (shared): Embedding(32128, 768)
      (encoder): T5Stack(
        (embed_tokens): Embedding(32128, 768)
        (block): ModuleList(
          (0): T5Block(
            (layer): ModuleList(
              (0): T5LayerSelfAttention(
                (SelfAttention): T5Attention(
                  (q): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (k): Linear(in_features=768, out_features=768, bias=False)
                  (v): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (o): Linear(in_features=768, out_features=768, bias=False)
                  (relative_attention_bias): Embedding(32, 12)
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (1): T5LayerFF(
                (DenseReluDense): T5DenseGatedActDense(
                  (wi_0): Linear(in_features=768, out_features=2048, bias=False)
                  (wi_1): Linear(in_features=768, out_features=2048, bias=False)
                  (wo): Linear(in_features=2048, out_features=768, bias=False)
                  (dropout): Dropout(p=0.1, inplace=False)
                  (act): NewGELUActivation()
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
          (1-11): 11 x T5Block(
            (layer): ModuleList(
              (0): T5LayerSelfAttention(
                (SelfAttention): T5Attention(
                  (q): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (k): Linear(in_features=768, out_features=768, bias=False)
                  (v): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (o): Linear(in_features=768, out_features=768, bias=False)
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (1): T5LayerFF(
                (DenseReluDense): T5DenseGatedActDense(
                  (wi_0): Linear(in_features=768, out_features=2048, bias=False)
                  (wi_1): Linear(in_features=768, out_features=2048, bias=False)
                  (wo): Linear(in_features=2048, out_features=768, bias=False)
                  (dropout): Dropout(p=0.1, inplace=False)
                  (act): NewGELUActivation()
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
        (final_layer_norm): T5LayerNorm()
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (decoder): T5Stack(
        (embed_tokens): Embedding(32128, 768)
        (block): ModuleList(
          (0): T5Block(
            (layer): ModuleList(
              (0): T5LayerSelfAttention(
                (SelfAttention): T5Attention(
                  (q): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (k): Linear(in_features=768, out_features=768, bias=False)
                  (v): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (o): Linear(in_features=768, out_features=768, bias=False)
                  (relative_attention_bias): Embedding(32, 12)
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (1): T5LayerCrossAttention(
                (EncDecAttention): T5Attention(
                  (q): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (k): Linear(in_features=768, out_features=768, bias=False)
                  (v): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (o): Linear(in_features=768, out_features=768, bias=False)
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (2): T5LayerFF(
                (DenseReluDense): T5DenseGatedActDense(
                  (wi_0): Linear(in_features=768, out_features=2048, bias=False)
                  (wi_1): Linear(in_features=768, out_features=2048, bias=False)
                  (wo): Linear(in_features=2048, out_features=768, bias=False)
                  (dropout): Dropout(p=0.1, inplace=False)
                  (act): NewGELUActivation()
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
          (1-11): 11 x T5Block(
            (layer): ModuleList(
              (0): T5LayerSelfAttention(
                (SelfAttention): T5Attention(
                  (q): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (k): Linear(in_features=768, out_features=768, bias=False)
                  (v): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (o): Linear(in_features=768, out_features=768, bias=False)
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (1): T5LayerCrossAttention(
                (EncDecAttention): T5Attention(
                  (q): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (k): Linear(in_features=768, out_features=768, bias=False)
                  (v): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.1, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (o): Linear(in_features=768, out_features=768, bias=False)
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (2): T5LayerFF(
                (DenseReluDense): T5DenseGatedActDense(
                  (wi_0): Linear(in_features=768, out_features=2048, bias=False)
                  (wi_1): Linear(in_features=768, out_features=2048, bias=False)
                  (wo): Linear(in_features=2048, out_features=768, bias=False)
                  (dropout): Dropout(p=0.1, inplace=False)
                  (act): NewGELUActivation()
                )
                (layer_norm): T5LayerNorm()
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
        (final_layer_norm): T5LayerNorm()
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (lm_head): Linear(in_features=768, out_features=32128, bias=False)
    )
  )
)

### 7.2 Generate on Validation Set

In [2]:
from torch.utils.data import DataLoader

def generate_predictions(model, dataset, tokenizer, batch_size=96, max_new_tokens=64, num_beams=4):
    """Runs beam-search generation over `dataset` and returns (predictions, references)."""
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    predictions, references = [], []
    model.eval()

    for batch in loader:
        inputs = tokenizer(
            batch["prompt"],
            padding=True,
            truncation=True,
            max_length=384,
            return_tensors="pt",
        ).to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                num_beams=num_beams,
                do_sample=False,
            )

        preds = tokenizer.batch_decode(outputs, skip_special_tokens=True)
        predictions.extend(preds)
        references.extend(batch["target"])

    return predictions, references

In [5]:
ft_predictions, ft_references = generate_predictions(
    fine_tuned_model, dataset["validation"], tokenizer
)
print(f"Generated {len(ft_predictions)} predictions with the fine-tuned model.")

Generated 7700 predictions with the fine-tuned model.

In [6]:
import gc

# Free VRAM held by the fine-tuned model before loading a second full model
fine_tuned_model.to("cpu")
gc.collect()
torch.cuda.empty_cache()

base_model_for_eval = AutoModelForSeq2SeqLM.from_pretrained(
    "./models/flan-t5-base-local",
    device_map="auto",
    trust_remote_code=True,
    dtype=torch.bfloat16,
)
base_model_for_eval.eval()

base_predictions, base_references = generate_predictions(
    base_model_for_eval, dataset["validation"], tokenizer
)
print(f"Generated {len(base_predictions)} predictions with the base (non-fine-tuned) model.")

# References are identical for both models (same dataset, same order) 
assert base_references == ft_references

Loading weights: 100%|██████████| 282/282 [00:00<00:00, 1408.72it/s]
[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

Generated 7700 predictions with the base (non-fine-tuned) model.

In [ ]:
import evaluate
import nltk

# METEOR needs these NLTK resources the first time it runs
nltk.download("wordnet", quiet=True)
nltk.download("omw-1.4", quiet=True)
nltk.download("punkt", quiet=True)
nltk.download("punkt_tab", quiet=True)

rouge_metric = evaluate.load("rouge")
bleu_metric = evaluate.load("bleu")
meteor_metric = evaluate.load("meteor")
bertscore_metric = evaluate.load("bertscore")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Youssef\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Youssef\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Youssef\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [8]:
def compute_all_metrics(predictions, references, label="model"):
    """Computes ROUGE-L, BLEU, METEOR, BERTScore-F1, and (optionally) BLEURT for one set
    of generated predictions against their references."""

    def sanitize(texts, placeholder="[empty]"):
        # bert_score (and some metric libs) crash or misbehave on empty/whitespace-only
        # strings depending on the installed transformers version. Empty generations are
        # also a real signal (esp. from a zero-shot base model giving up early) worth
        # counting rather than silently dropping.
        cleaned, n_empty = [], 0
        for t in texts:
            if t is None or t.strip() == "":
                cleaned.append(placeholder)
                n_empty += 1
            else:
                cleaned.append(t)
        return cleaned, n_empty

    predictions, n_empty_preds = sanitize(predictions)
    references, n_empty_refs = sanitize(references)
    if n_empty_preds or n_empty_refs:
        print(
            f"[{label}] sanitized {n_empty_preds} empty prediction(s) and "
            f"{n_empty_refs} empty reference(s) before scoring."
        )

    refs_list = [[r] for r in references]  # bleu/meteor expect a list of references per example

    rouge_res = rouge_metric.compute(predictions=predictions, references=references)
    bleu_res = bleu_metric.compute(predictions=predictions, references=refs_list)
    meteor_res = meteor_metric.compute(predictions=predictions, references=references)
    bertscore_res = bertscore_metric.compute(
        predictions=predictions, references=references, lang="en"
    )

    results = {
        "model": label,
        "ROUGE-L": rouge_res["rougeL"],
        "BLEU": bleu_res["bleu"],
        "METEOR": meteor_res["meteor"],
        "BERTScore-F1": sum(bertscore_res["f1"]) / len(bertscore_res["f1"]),
    }

    return results

In [10]:
import pandas as pd

base_results = compute_all_metrics(base_predictions, base_references, label="Base (no fine-tuning)")
ft_results = compute_all_metrics(ft_predictions, ft_references, label="Fine-tuned (QLoRA)")

results_df = pd.DataFrame([base_results, ft_results]).set_index("model")
results_df

[Base (no fine-tuning)] sanitized 4 empty prediction(s) and 0 empty reference(s) before scoring.
[Fine-tuned (QLoRA)] sanitized 1 empty prediction(s) and 0 empty reference(s) before scoring.

                        ROUGE-L      BLEU    METEOR  BERTScore-F1
model
Base (no fine-tuning)  0.191407  0.046260  0.210843      0.855862
Fine-tuned (QLoRA)     0.381938  0.171166  0.410853      0.903964